apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJkbUZ6YVd4cGVURXpNRFU2WjJod1gxbFBNa2wyY1RoMmVYVTNaMmxwYXpWbWNGUktiVTlSY25oMU1YUlpNVEZMWjNSd2R3PT0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
