apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkbUZ6YVd4cGVURXpNRFU2WjJod1gxbFBNa2wyY1RoMmVYVTNaMmxwYXpWbWNGUktiVTlSY25oMU1YUlpNVEZMWjNSd2R3PT0iCgkJfQoJfQp9
  
type: kubernetes.io/dockerconfigjson
