apiVersion: v1
kind: Secret
metadata:
  name: cinemaabyss-secrets
  namespace: cinemaabyss
type: Opaque
data:
  # Base64 encoded values
  # echo -n "postgres_password" | base64
  DB_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=